name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test-accounts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run flake8
        run: poetry run flake8 src
      - name: Run accounts tests
        run: poetry run pytest src/tests/test_integration/test_accounts.py

  test-movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run movies tests
        run: poetry run pytest src/tests/test_integration/test_movies.py

  test-profiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run profiles tests
        run: poetry run pytest src/tests/test_integration/test_profiles.py

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Start Docker Compose
        run: docker compose -f docker-compose-tests.yml up --build --abort-on-container-exit --exit-code-from web
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose-tests.yml down

  deploy:
    runs-on: ubuntu-latest
    needs: [test-accounts, test-movies, test-profiles, test-e2e]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            PROJECT_DIR="/home/ubuntu/src/py-fastapi-homework-5-ec2-deploy-task"
            
            if [ ! -d "$PROJECT_DIR/.git" ]; then
              sudo rm -rf $PROJECT_DIR
              git clone https://github.com/${{ github.repository }}.git $PROJECT_DIR
            fi
            
            cd $PROJECT_DIR
            git pull origin main
            
            sudo docker-compose -f docker-compose-prod.yml down || true
            sudo docker-compose -f docker-compose-prod.yml up -d
